services:
  embedding_runner:
    build: .
    command: >
      sh -c "
        rm -f /app/data_store/vector_store_ready
        python daily_script_runner.py
      "
    volumes:
      - vector_data:/app/data_store
      - logs_data:/app/logs
    restart: "no"

  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for vector store readiness flag...'
        echo 'Loading newsletter data into vector store. This may take a few minutes...'
        while [ ! -f /app/data_store/vector_store_ready ]; do
          sleep 5
        done
        echo 'Vector store ready, starting web app...'
        uvicorn cli:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"
    volumes:
      - vector_data:/app/data_store
      - logs_data:/app/logs
    depends_on:
      - embedding_runner
    restart: unless-stopped

volumes:
  vector_data:
  logs_data:
